title: main
email: ramon@b1t.dev
description: A directory of my projects. 
baseurl: "/"
url: "https://b1t.dev" 
github_username:  RamonAsuncion
encoding: utf-8
timezone: America/New_York
sass:
  sass_dir: ./_scss
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
