title: main
email: email@example.com
description: A description of the site
baseurl: "/"
url: "https://example.com"
github_username:  GithubUsername
encoding: utf-8
timezone: America/New_York
sass:
  sass_dir: ./_scss
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
